site_name: OI Beats
theme:
    name: "material"
    logo: images/logo.svg
    icon: images/logo.svg
    palette:
        primary: "black"
        accent: "deep orange"
    language: "zh"
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css